# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='buyer_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_card', to='cards.Card'),
        ),
        migrations.AddField(
            model_name='payment',
            name='seller_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_card', to='cards.Card'),
        ),
    ]
