# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Payments Manager
  description: Transafe payments manager service API
  version: "0.0.1"
# the domain of the service
host: 192.168.33.10
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /api/v1
produces:
  - application/json
paths:
  /payments_create_interface:
    get:
      summary: Get HTML page to confirm payment.
      description: |
        This payments endpoint method returns all the information about a payment that a user defined by a uuid has associated to him
      parameters:
        - name: uuid1
          description: The uuid of user1
          required: true
          type: string
          in: header
        - name: uuid2
          description: The uuid of user2
          required: true
          type: string
          in: header
        - name: user1_name
          description: The user1 name
          required: true
          type: string
          in: header
        - name: user2_name
          description: The user2 name
          required: true
          type: string
          in: header
        - name: amount
          description: The amount of money to pay
          required: true
          type: number
          in: header
        - name: description
          description: Description of the transaction
          required: true
          type: string
          in: header
      tags:
        - Payments
      responses:
        200:
          description: Retunrs an html page.
        default:
          description: Unexpected Error.
  /payments:
    get:
      summary: Get payments per user.
      description: |
        This payments endpoint method returns all payments that a user defined by a uuid has associated to him
      parameters:
        - name: uuid
          description: The user uuid
          required: true
          type: string
          in: header
      tags:
        - Payments
      responses:
        200:
          description: A json array with all of the user payments
        default:
          description: Unexpected error
  
    post:
      summary: Create a new payment for an user
      description: |
        This payments endpoint method is used to create a new payment to the user specified by the uuid.
      parameters:
        - name: buyer_uuid
          description: The buyer uuid
          required: true
          type: string
          in: header
        - name: seller_uuid
          description: The seller uuid
          required: true
          type: string
          in: header
        - name: transaction_id
          description: Transaction id
          required: true
          type: string
          in: header
        - name: amount
          description: The amount of money to pay
          required: true
          type: number
          in: header
        - name: description
          description: Description of the product
          required: true
          type: string
          in: header
      tags:
        - Payments
      responses:
        200:
          description: Returns the paymentID
        401:
          description: Client doesn't have enough money to pay.
        default:
          description: Unexpected error
    
  /payments/{paymentID}:
    get:
      summary: Get payment by ID.
      description: |
        This payments endpoint method returns all the information about a payment
      parameters:
        - name: paymentID
          description: The payment id
          required: true
          type: string
          in: path
        - name: user_uuid
          description: Uuid of the logged user
          required: true
          type: string
          in: header
      tags:
        - Payments
      responses:
        200:
          description: A json array with the information of a payment
        401:
          description: The payment ID doesn't correspond to user's uuid.
        default:
          description: Unexpected error
          
    put:
      summary: Update payment state.
      description: |
        This payments endpoint method updates all the information about a payment
      parameters:
        - name: paymentID
          description: The payment id
          required: true
          type: string
          in: path
        - name: user_uuid
          description: Uuid of the logged user
          required: true
          type: string
          in: header
        - name: operation
          description: Operation to be done, finish the payment or refund the buyer. The state can be Pending, Finished or Refunded.
          required: true
          type: string
          in: header
      tags:
        - Payments
      responses:
        200:
          description: Payment state have been updated successfully.
        401:
          description: The payment ID doesn't correspond to user's uuid.
        default:
          description: Unexpected error
          
  /sells:
    get:
      summary: Get sells per user.
      description: |
        This sells endpoint method returns all sells that a user defined by a uuid has associated to him, either present or
      parameters:
        - name: uuid
          description: The user uuid
          required: true
          type: string
          in: header
      tags:
        - Sells
      responses:
        200:
          description: A json array with all of the user sells
        default:
          description: Unexpected error
  
  /cards/create/:
    post:
      summary: Get URL to add a new card
      description: |
        This cards endpoint method returns an URL that an user defined by a uuid has associated to him can associate a credit card
      parameters:
        - name: user_id
          description: The user uuid
          required: true
          type: string
          in: header
      tags:
        - Cards
      responses:
        302:
          description: The card has been associated successfully.
        default:
          description: Unexpected error
          
  /cards/update/:
    post:
      summary: Get URL to update a card
      description: |
        This cards endpoint method returns an URL that an user defined by a uuid has associated to him can update a credit card
      parameters:
        - name: user_id
          description: The user uuid
          required: true
          type: string
          in: header
      tags:
        - Cards
      responses:
        302:
          description: The card has been associated successfully.
        default:
          description: Unexpected error
          
  /cards/delete/:
    post:
      summary: Get URL to delete a card
      description: |
        This cards endpoint method returns an URL that an user defined by a uuid has associated to him can delete a credit card
      parameters:
        - name: user_id
          description: The user uuid
          required: true
          type: string
          in: header
      tags:
        - Cards
      responses:
        302:
          description: Redirect URL.
        default:
          description: Unexpected error
  
  
 
          
  