# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Payments Manager
  description: Transafe payments manager service API
  version: "0.0.1"
# the domain of the service
host: 192.168.33.10
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /api/v1
produces:
  - application/json
paths:
  /payments/create:
    post:
      summary: Create a new payment for an user
      description: |
        This payments endpoint method is used to create a new payment to the user specified by the uuid.
      parameters:
        - name: token_ID
          description: The application token ID
          required: true
          type: string
          in: header
        - name: user_id1
          description: The user_id1 uuid
          required: true
          type: string
          in: formData
        - name: user_id2
          description: The user_id2 uuid
          required: true
          type: string
          in: formData
        - name: transaction_id
          description: Transaction id
          required: true
          type: string
          in: formData
        - name: amount
          description: The amount of money to pay
          required: true
          type: number
          in: formData
        - name: description
          description: Description of the product
          required: true
          type: string
          in: formData
        - name: callback
          description: URL to redirect
          required: true
          type: string
          in: formData
      tags:
        - Payments
      responses:
        302:
          description: Redirect to the page to confirm the payment
        default:
          description: Unexpected error
    
  /payments/complete:
    post:
      summary: Complete payment.
      description: |
        This payments endpoint method completes the payment
      parameters:
        - name: token_ID
          description: The application token ID
          required: true
          type: string
          in: header
        - name: transaction_id
          description: The transaction id
          required: true
          type: string
          in: formData
      tags:
        - Payments
      responses:
        200:
          description: The payment has been completed succesfully
        401:
          description: This transaction can't be completed 
        default:
          description: Unexpected error
          
  /payments/refund:
    post:
      summary: Refund payment
      description: |
        This payments endpoint method refunds the payment
      parameters:
        - name: token_ID
          description: The application token ID
          required: true
          type: string
          in: header
        - name: transaction_id
          description: The transaction id
          required: true
          type: string
          in: formData
      tags:
        - Payments
      responses:
        200:
          description: The payment has been refunded succesfully
        401:
          description: This transaction can't be refunded 
        default:
          description: Unexpected error
  
  /cards/mycards/{user_id}:
    get:
      summary: Get URL to see my cards
      description: |
        This cards endpoint method returns an URL that an user defined by a uuid has associated to him can see his cards
      parameters:
        - name: user_id
          description: The user uuid
          required: true
          type: string
          in: path
      tags:
        - Cards
      responses:
        302:
          description: Redirect URL.
        default:
          description: Unexpected error
  
 
          
  