# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-03 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(default=uuid.uuid4, max_length=128, unique=True)),
                ('name', models.CharField(default=b'Sandbox', max_length=128)),
            ],
        ),
    ]
