# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 15:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128)),
                ('number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(b'^[0-9]+$', b'Only Numbers')])),
                ('expire_month', models.IntegerField()),
                ('expire_year', models.IntegerField()),
                ('cvv2', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(b'^[0-9]+$', b'Only Numbers')])),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
            ],
        ),
    ]
