# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-30 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='total',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=7),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together=set([('user_id', 'number', 'cvv2')]),
        ),
    ]
