# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-30 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20160930_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_id',
            field=models.CharField(default=uuid.uuid4, max_length=128),
        ),
    ]
