# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20160930_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
